name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install flet yfinance pandas numpy
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-venv build-essential git zip
        sudo apt-get install -y libffi-dev libssl-dev
        sudo apt-get install -y python3-setuptools python3-wheel
        pip install buildozer cython

    - name: Build APK
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        buildozer init
        cp buildozer.spec buildozer.spec.bak
        cp buildozer.spec.bak buildozer.spec
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: StockFetcher-APK
        path: bin/*.apk
